name: Publish releases to npm

on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: windows-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Get version
        run: echo "TAG_VERSION=${{github.ref}}"
